### ISSUE TITLE
State is saved is non-atomic manner

### ISSUE THREAD

**Issue by artyom** [rsc/letsencrypt#10]
Currently for persistence non-atomic dump is made using ioutil.WriteFile which truncates the state file before overwriting it. This theoretically can lead to state file corruption (imagine disk filled to its capacity by other process which write succeeds between truncate and write issued by `ioutil.WriteFile`). This can be fixed by replacing ioutil.WriteFile call with write to a separate temporary file in the same directory + atomic file state replacement with os.Rename.

**Comment by rsc** [comment]
See https://godoc.org/rsc.io/letsencrypt#hdr-Warning. Thanks.
