### ISSUE TITLE
X509 issues within docker containers

### ISSUE THREAD

**Issue by doejon** [rsc/letsencrypt#16]
Hi there!
While running your package within a docker container I encountered an issue regarding X509 certs.
Since most docker containers don't require ca-certificates (e.g. by running apt-get install ca-certificates) by default you'll never be able to run rsc/letsencrypt as a standalone application (since it depends on ca-certificates). https://github.com/kelseyhightower/contributors provides a nice workaround which did not quite work since some of the vendor libraries (I believe it's acme) uses tls to call letsencrypt. As a quick-and-dirty solution I'm creating a ca-certificates.crt myself by using coreos' certs (pemCerts, found in /etc/ssl/certs/ca-certificates.crt):

```
const CertPath = "/etc/ssl/certs/"
const CertFile = "ca-certificates.crt"

//Try to write ca-certificates to file
func CreateCertFile() {
    if _, err := os.Stat(CertPath + CertFile); os.IsNotExist(err) {
        log.Println("Writing certs file...")
        if err := os.MkdirAll(CertPath, 0644); err != nil {
            panic(err)
        }
        if err := ioutil.WriteFile(CertPath+CertFile, pemCerts, 0644); err != nil {
            panic(err)
        }
        log.Println("Wrote certs file to " + CertPath)
    }
}
```

Any other chance to make your awesome library independent from system files?

Cheers
Korbi

**Comment by rsc** [comment]
The system should be in charge of providing the root set, not this library. The solution is to get certs into your docker container explicitly.
