### ISSUE TITLE
Vendor all dependencies

### ISSUE THREAD

**Issue by mibk** [rsc/letsencrypt#2]
Shouldn't all dependencies be in vendor directory? I noticed the following packages aren't:
- golang.org/x/crypto/ocsp  
-  golang.org/x/net/context  
-  golang.org/x/time/rate

**Comment by rsc** [comment]
I vendored the ones that I was worried about changing underfoot in incompatible ways, or that I'd made local modification to. I am not worried about the golang.org/x ones.

**Comment by mibk** [comment]
Understood. I wanted to find out what is the best practice anyway. Thanks for the clarification :-)
