### ISSUE TITLE
Library does not work with latest version of xenolf/lego

### ISSUE THREAD

**Issue by Willyham** [rsc/letsencrypt#22]
I understand that the dependencies are vendored, but it would be nice to update this to work with the latest version of `lego` which removes the `TLSSNI01ChallengeCertDomain` function:

https://github.com/xenolf/lego/commit/be785fda33e77a193c5e1428a97b1ef4a0fd8886

This would allow consumers to install with `--strip-vendor`.

**Comment by rsc** [comment]
Dup of #15 / #18.
