### ISSUE TITLE
Error in vendored acme package

### ISSUE THREAD

**Issue by wscherfel** [rsc/letsencrypt#23]
Hello,

it seems that you have following errors in your vendored acme package:
```
rsc/letsencrypt/lets.go:674: not enough arguments in call to c.ObtainCertificate
rsc/letsencrypt/lets.go:731: undefined: acme.TLSSNI01ChallengeCertDomain
rsc/letsencrypt/lets.go:744: undefined: acme.TLSSNI01ChallengeCertDomain
```

Do you know which commit of acme should i use so this does not occur?

**Comment by rsc** [comment]
The copy vendored in this repo is the one to use. It does not correspond to a commit in the standard acme package. See #15/#18. Sorry for the confusion.
