### ISSUE TITLE
please re-vendor xenolf/lego

### ISSUE THREAD

**Issue by onlyjob** [rsc/letsencrypt#27]
[xenolf/lego](https://github.com/xenolf/lego) is a semantically versioned library so it would be ideal to vendor by tag/release instead of random commit:

 https://github.com/rsc/letsencrypt/blob/master/vendor/vendor.json#L9-L10

Please upgrade _xenolf/lego_ and vendor it by tag.

**Comment by rsc** [comment]
See https://godoc.org/rsc.io/letsencrypt#hdr-Warning. Thanks.
