### ISSUE TITLE
Update to lego v2

### ISSUE THREAD

**Issue by eclipseo** [rsc/letsencrypt#28]
Could you please update letsencrypt to use the v2 of https://github.com/go-acme/lego. It would help distro integrators greatly.
Also please consider converting to Go modules.

**Comment by rsc** [comment]
See https://godoc.org/rsc.io/letsencrypt#hdr-Warning. Thanks.

**Comment by eclipseo** [comment]
Sadly it's a dependency of github.com/docker/distribution

**Comment by rsc** [comment]
Sadly, docker/distribution has been using this UNTESTED, UNSUPPORTED package in an apparently SECURITY-CRITICAL CONTEXT since 2016. Not sure what that says about Docker Distribution, but nothing good. https://github.com/rsc/letsencrypt/issues/15#issuecomment-252427783
